export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_POST = 'RECEIVE_POST';
export const RECEIVE_POST_PENDING = 'RECEIVE_POST_PENDING';
export const RECEIVE_POST_FAIL = 'RECEIVE_POST_FAIL';
export const ADD_POST = 'ADD_POST';
export const VOTE_POST = 'VOTE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const SORT_POST = 'SORT_POST';
